services:
  db:
    image: postgres:15
    container_name: pg-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pr-chat-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: pr-chat-bot
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "8697:8697"
    restart: unless-stopped
    environment:
      HTTP_LISTEN_ADDRESS: "${HTTP_LISTEN_ADDRESS}"
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      PG_DSN: "${PG_DSN}"
      AI_URL: "${AI_URL}"
      AI_KEY: "${AI_KEY}"
      DB_HOST: pg-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: app_db
    networks:
      - pr-chat-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  pgdata:

networks:
  pr-chat-net:
    driver: bridge
