name: Build Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t pr-chat-bot -f .docker/Dockerfile .

      - name: Stop and remove old containers
        continue-on-error: true
        run: |
          docker rm -f pr-chat-bot || true
          docker rm -f pg-db || true

      - name: Run PostgreSQL container
        run: |
          docker run -d \
            --name pg-db \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=postgres \
            -e POSTGRES_DB=app_db \
            -p 5432:5432 \
            postgres:15

      - name: Run container in background
        run: |
          docker run -d \
            --name pr-chat-bot \
            -p 8080:8080 \
            -p 8697:8697 \
            -e HTTP_LISTEN_ADDRESS=${{ secrets.HTTP_LISTEN_ADDRESS }} \
            -e JWT_PRIVATE_KEY="${{ secrets.JWT_PRIVATE_KEY }}" \
            -e JWT_PUBLIC_KEY="${{ secrets.JWT_PUBLIC_KEY }}" \
            -e TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} \
            -e TG_CERTIFICATE="${{ secrets.TG_CERTIFICATE }}" \
            -e TG_KEY="${{ secrets.TG_KEY }}" \
            -e DB_HOST=pg-db \
            -e DB_PORT=5432 \
            -e DB_USER=postgres \
            -e DB_PASSWORD=postgres \
            -e DB_NAME=app_db \
            pr-chat-bot
