name: Deploy to Localhost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "HTTP_LISTEN_ADDRESS=${{ secrets.HTTP_LISTEN_ADDRESS }}" > .env
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
          echo "PG_DSN=${{ secrets.PG_DSN }}" >> .env
          echo "AI_URL=${{ secrets.AI_URL }}" >> .env
          echo "AI_KEY=${{ secrets.AI_KEY }}" >> .env

      - name: Stop and remove running containers
        run: docker compose down || true

      - name: Build and start containers
        run: docker compose up -d --build

      - name: Show running containers
        run: docker ps
